### ISSUE TITLE
crash - failed to find valid wander position in the end

### ISSUE THREAD

**Issue by kittenvr** [MiranCZ/altoclef#1]
## Steps to Reproduce (as best as you can)
idk was afk when crached but i was using gamer

## Crashlogs and Screenshots (if applicable)

https://paste.gg/p/PizzaV/e368e956c691477b85aeaef03562e41f
_(you may drag + drop text logs and images here, thanks GitHub)_

## Other mods (if applicable)
- [Reese's Sodium Options](https://github.com/FlashyReese/reeses-sodium-options) [1.7.0+mc1.20.2-build.97]
- [Entity Texture Features](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric) [4.6.1]
- MoreChatHistory [1.1.1]
- [Controlify](https://isxander.dev) [1.7.0+1.20.2]
- [No Chat Reports](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports) [1.20.2-v2.3.1]
- [Animatica](https://github.com/FoundationGames/Animatica) [0.6+1.20]
- [Sodium](https://github.com/CaffeineMC/sodium-fabric) [0.5.3]
- [YetAnotherConfigLib](https://isxander.dev) [3.2.1+1.20.2]
- ImmediatelyFast [1.2.7+1.20.2]
- [Fabric Language Kotlin](https://minecraft.curseforge.com/projects/fabric-language-kotlin) [1.10.16+kotlin.1.9.21]
- [Dynamic FPS](https://dapprgames.com/mods/) [3.2.1]
- [LambDynamicLights](https://modrinth.com/mod/lambdynamiclights) [2.3.3+1.20.2]
- [Fabrishot](https://github.com/ramidzkh/fabrishot#readme) [1.10.0]
- [Mod Menu](https://modrinth.com/mod/modmenu) [8.0.0]
- [MixinTrace](https://modrinth.com/mod/mixintrace) [1.1.1+1.17]
- [More Culling](https://github.com/fxmorin/moreculling) [1.20.1-0.19.0]
- FabricSkyBoxes Interop [1.3.6+mc1.20.2-build.52]
- FabricSkyBoxes [0.7.3+mc1.20.2]
- [Language Reload](https://modrinth.com/mod/language-reload) [1.5.10+1.20.2]
- [e4mc](https://e4mc.link) [4.0.1]
- [Lithium](https://jellysquid.me/projects/) [0.12.0]
- [OptiGUI](https://opekope2.github.io/OptiGUI) [2.1.6]
- [Enhanced Block Entities](https://github.com/FoundationGames/EnhancedBlockEntities) [0.9.1+1.20.2]
- [Zoomify](https://isxander.dev) [2.12.0]
- [Continuity](https://modrinth.com/mod/continuity) [3.0.0-beta.4+1.20.2]
- [Debugify](https://isxander.dev) [1.20.2+1.0]
- [Cloth Config v12](https://minecraft.curseforge.com/projects/cloth-config) [12.0.111]
- YOSBR [0.1.2]
- [Fabric API](https://fabricmc.net) [0.91.1+1.20.2]
- [Indium](https://modrinth.com/mod/indium) [1.0.27+mc1.20.1]
- [Remove Reloading Screen](https://curseforge.com/minecraft/mc-mods/rrls) [3.2.3+mc1.20.2-fabric]
- Better Mount HUD [1.2.2]
- [ModernFix](https://modrinth.com/mod/modernfix) [5.10.0+mc1.20.2]
- [Puzzle](https://www.midnightdust.eu/) [1.6.0+1.20.2]
- [CIT Resewn](https://citresewn.shcm.io/) [1.1.3+1.20]
- [Main Menu Credits](https://isxander.dev) [1.1.2]
- [Iris](https://github.com/IrisShaders/Iris) [1.6.10]
- [Paginated Advancements](https://github.com/DaFuqs/) [2.4.2]
- [Sodium Extra](https://modrinth.com/mod/sodium-extra) [0.5.3+mc1.20.2-build.114]
- [Entity Model Features](https://www.curseforge.com/minecraft/mc-mods/entity-model-features) [1.1.0]
- [Model Gap Fix](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix) [1.14]
- [FastQuit](https://modrinth.com/mod/fastquit) [3.0.0+1.20+]
- [EntityCulling-Fabric](https://github.com/tr7zw/EntityCulling-Fabric) [1.6.2-mc1.20.1]
- [Capes](https://www.curseforge.com/minecraft/mc-mods/capes) [1.5.3+1.20.2]
- [Borderless Mining](https://github.com/comp500/BorderlessMining) [1.1.9+1.20.2]
- [FerriteCore](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric) [6.0.1]
- [Alto Clef](https://fabricc.net/) [1.20.2-beta1]

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by kittenvr** [comment]
another crash 
[latest.log](https://github.com/MiranCZ/altoclef/files/15048065/latest.log)

**Comment by MiranCZ** [comment]
Oh, thats a lot of mods you got there...
Where were you when the crash happened and what was the bot doing? There seems to be some problem with the `KillEnderDragonTask`

**Comment by MiranCZ** [comment]
I assume you were in the end.
It seems like the bot failed to find any valid spot to go to... 
Could you send the seed, or somehow show where you were? It seems pretty unusual for this to happen

**Comment by kittenvr** [comment]
the ip is play.volcanware.xyz

**Comment by MiranCZ** [comment]
It would be more helpful if you just described the issue.. also, the bot is optimized for speedrunning and assumes a lot of stuff because of that, so if you are playing with a lot of mods on a public server strictly not singleplayer I see why it could fail

**Comment by MiranCZ** [comment]
Basically what is happening is that the bot checks a radius around it for endstone and then goes to that location.
But it seems it didnt find any valid location in your case, please provide more information or I will just have to close this issue because playing on servers is not the focus of this repository...

**Comment by MiranCZ** [comment]
Closing this for now. If the problem persists feel free to open a new issue with more information.

**Comment by kittenvr** [comment]
> Basically what is happening is that the bot checks a radius around it for endstone and then goes to that location.
> But it seems it didnt find any valid location in your case, please provide more information or I will just have to close this issue because playing on servers is not the focus of this repository...

The end is lava casted

**Comment by MiranCZ** [comment]
Oh, well, as I said, this is (at least not right now) the focus of this mod
