### ISSUE TITLE
Gets stuck in powdered snow

### ISSUE THREAD

**Issue by K0shachiyamyatA** [MiranCZ/altoclef#2]
## Steps to Reproduce (as best as you can)
get to powdered snow biome
## Expected Behavior
avoid powdered snow
## Actual Behavior (What lead to the bot getting permanently stuck)
baritone walks right into it and gets stuck like an idiot, despite it being in the blacklist
## Crashlogs and Screenshots (if applicable)
https://github.com/MiranCZ/altoclef/assets/88767403/3241c902-c214-4942-81ba-5c51b863754e
_(you may drag + drop text logs and images here, thanks GitHub)_

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by MiranCZ** [comment]
Thank you for the report, I will 100% look into this!

**Comment by MiranCZ** [comment]
should be fixed with [the new release](https://github.com/MiranCZ/altoclef/releases/tag/1.20.2-0.12) by [improved UnstuckChain and added case for getting stuck in powdered snow](https://github.com/MiranCZ/altoclef/commit/1e8dfffb706224d9f2e6a012f405831f82b26901)
