### ISSUE TITLE
Gets killed by brutes in bastion (hard difficulty)

### ISSUE THREAD

**Issue by K0shachiyamyatA** [MiranCZ/altoclef#3]
## Steps to Reproduce (as best as you can)
set baritone path through bastion
## Expected Behavior
avoid bastions at all costs
## Actual Behavior (What lead to the bot getting permanently stuck)
tries to fight two brutes head-on lmao
## Crashlogs and Screenshots (if applicable)

https://github.com/MiranCZ/altoclef/assets/88767403/af84aa62-b10b-41e9-a3cc-0a4e2a858e39

_(you may drag + drop text logs and images here, thanks GitHub)_

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by MiranCZ** [comment]
Yeah, thats definitely an issue. Not sure what I can do about it without editing baritones code...
I see you are playing on hardcore btw, you should try playing on easy, since mobs deal way less damage.

**Comment by MiranCZ** [comment]
I will close this as not planned for now... Might reopen it in the future, but this is out of scope for now because I would probably have to go trough and edit baritones code...
