### ISSUE TITLE
Gets stuck in flowing water when mining

### ISSUE THREAD

**Issue by K0shachiyamyatA** [MiranCZ/altoclef#4]
## Steps to Reproduce (as best as you can)
add some water to the bot's mine
## Expected Behavior
do not get stuck
## Actual Behavior (What lead to the bot getting permanently stuck)
gets stuck
## Crashlogs and Screenshots (if applicable)

https://github.com/MiranCZ/altoclef/assets/88767403/a4204f54-df98-4aec-b8e8-ed3856a3965b

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by MiranCZ** [comment]
Yeah, baritone has problems with water (and Altoclef also isnt great in it)...
I could try to change the way it pickups water, so that it only collects it from the top and doesnt flood itself

**Comment by MiranCZ** [comment]
Altough when looking at the video, didnt it get unstuck after a bit? I think I was already adding some unstuck mechanism for cases like this...

**Comment by K0shachiyamyatA** [comment]
> Altough when looking at the video, didnt it get unstuck after a bit? I think I was already adding some unstuck mechanism for cases like this...

Nope, i waited for solid 10 minutes.

**Comment by MiranCZ** [comment]
> Nope, i waited for solid 10 minutes.
Oh, aight.. I will try to look at it then!

**Comment by MiranCZ** [comment]
should be fixed with [the new release](https://github.com/MiranCZ/altoclef/releases/tag/1.20.2-0.12) by [fixed CollectBucketLiquidTask collecting liquid blocks that would spill](https://github.com/MiranCZ/altoclef/commit/3fe4431edc957546965b85a6bdc2bd85dbd3c7fa)
