### ISSUE TITLE
Big Compilation (video timecodes)

### ISSUE THREAD

**Issue by K0shachiyamyatA** [MiranCZ/altoclef#5]
https://youtu.be/Zg2UkHzJtLE

bugs timecodes:
07:07 - lagg - **FIXED**
47:30 - strange food eating softlock - **FIXED**
59:13 - attack and runaway tasks conflict - **FIXED mostly**
1:04:51 - strange TimeoutWanderTask softlock - **FIXED, will be pushed soon**
01:12:06 - stopped collecting beds, didn't re-craft shield and other stuff, didn't sleep through the night, ran straight to the silverfish spawner :D - **FIXED**

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by MiranCZ** [comment]
Thank you for the report, really appriciate it!

For the lag, no idea what might have caused it... These things are really hard to debug 

I have never seem anything like the food eating glitch before.. Altough I will definitely need to investigate that 

The `TimeoutWanderTask` softlock also seems strange to me..

And oh boy, dont know if you realise but you found one of the rarest (and stupidest) bugs I think! :D
The bot constantly checks for the portal and if it founds it, it just goes there... 100% need to change that lmao 

Again, thank you for the report!

**Comment by MiranCZ** [comment]
For the food eating bug, a hotfix might be just something like checking if the bot is trying to eat for a suspiciously long time and the hunger isnt going up...

**Comment by MiranCZ** [comment]
Actually, for the lag I remember there being some commits saying that running a specific `ResourceTask` for too long on Hackerokuz's fork... Might be the issue, because the bot took a lot of time getting the pickace...

**Comment by MiranCZ** [comment]
For the lag, I found a memory leak in the code xd
Will try to fix and push that ASAP

**Comment by MiranCZ** [comment]
The memory leak should now be fixed in the [latest release](https://github.com/MiranCZ/altoclef/releases/latest)

**Comment by MiranCZ** [comment]
All of these should be (finally 😅) fixed!
