### ISSUE TITLE
Speedrun timer broken + water flood unstuck chain making the bot stuck (VIDEO)

### ISSUE THREAD

**Issue by K0shachiyamyatA** [MiranCZ/altoclef#6]
https://youtu.be/-toL7Vy1_J0
flood stuck in the end

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by MiranCZ** [comment]
Thank you for the report, I will try to fix that!

Also, what do you mean by "Speedrun timer broken"?

**Comment by K0shachiyamyatA** [comment]
> Thank you for the report, I will try to fix that!
> 
> Also, what do you mean by "Speedrun timer broken"?

It starts with 13 hours on it

**Comment by MiranCZ** [comment]
Oh, that definitely sounds like an issue xd

**Comment by MiranCZ** [comment]
the timer is fixed, will be pushed soon

**Comment by MiranCZ** [comment]
The timer not should work in the [latest release](https://github.com/MiranCZ/altoclef/releases/)

**Comment by MiranCZ** [comment]
Should be *kinda* fixed I guess? Will be pushed soon after more testing...

**Comment by MiranCZ** [comment]
Should be fixed, feel free to open a new issue if you find any more bugs
