### ISSUE TITLE
Voiding + Timewaste when Getting Endstone to Stack up to Endpillars

### ISSUE THREAD

**Issue by killerboyyy777** [MiranCZ/altoclef#8]
## Steps to Reproduce (as best as you can)
If the Bot reaches the End and Fails to onecycle the Dragon it trys to get the towers. At the Moment it runs out of Blocks it mines Endstone. 
## Expected Behavior
Mining Endstone picking up the Items to get Blocks and continue getting Towers
## Actual Behavior
doesnt Collect the Items and can fall into the void because its only mining blocks in its reach (slowly mining down)

_(you may drag + drop text logs and images here, thanks GitHub)_

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by killerboyyy777** [comment]
Dragon perched for a pretty short time and the bot didnt manage to place beds fast enough, was left with 2 beds and the dragon stopped perching and healed

**Comment by killerboyyy777** [comment]
sorry, misclicked

**Comment by MiranCZ** [comment]
Should be fixed by https://github.com/MiranCZ/altoclef/commit/b1201b6034d5adef4e7864dc075b4b4c19fd85c0
