### ISSUE TITLE
Stuck on Unstuck Task in underground water areas

### ISSUE THREAD

**Issue by killerboyyy777** [MiranCZ/altoclef#9]
## Steps to Reproduce (as best as you can)
Bot Builds straight down into a Underground water Area
## Expected Behavior
Bot swims to the Side of the Area or builds itself out of Water
## Actual Behavior (What lead to the bot getting permanently stuck)
Bot tries to Place a Block to no longer Stand in Water but fails to do it, continues trying forever until it dies because of hunger
## Crashlogs and Screenshots (if applicable)
Forgot to take Screenshots, faced this Problem multiple Times, adding Screenshots the next Time it happens

## Other mods (if applicable)
Other mods shouldnt be the Issue here.
Used: Entity Culling, ModernFix, Sodium

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by MiranCZ** [comment]
Thanks for the report!
Dang, I am really tempted to make my own water pathfinder because baritone really sucks with water lol

**Comment by killerboyyy777** [comment]
![2024-06-17_11 17 12](https://github.com/MiranCZ/altoclef/assets/133012114/8bdb23c3-8f71-4954-8f43-cc01ee60fc6f)
![2024-06-17_11 17 15](https://github.com/MiranCZ/altoclef/assets/133012114/cbd7564a-5661-4e25-84d8-090fb03e4cf7)
![2024-06-17_11 17 17](https://github.com/MiranCZ/altoclef/assets/133012114/1bd47cea-04cc-4b46-b701-82b76226e974)
![2024-06-17_11 17 19](https://github.com/MiranCZ/altoclef/assets/133012114/39d34537-7010-4bcb-9888-ce18c98e7766)
You cant really see it in the pics but its just spinning and trying to place a block

**Comment by killerboyyy777** [comment]
> Thanks for the report! Dang, I am really tempted to make my own water pathfinder because baritone really sucks with water lol

yeah baritone and water isnt a great combo

**Comment by MiranCZ** [comment]
should be (hopefully) fixed by https://github.com/MiranCZ/altoclef/commit/eb3f0cd527291b7b2677a554408a2ce36b388a14
If you still encounter the bot getting stuck feel free to open another issue
